### ISSUE TITLE
Document generics in base use case classes

### ISSUE THREAD

**Issue by Syex** [StefMa/UseKase#28]
Often when I'm adding a new use case and extend e.g. `SingleUseCase<R, P>` I'm wondering what is the input and what is the output, is it `R` or `P`? There's no documentation for those two. Maybe it would be even cooler to rename `R` and `P` to `Input` and `Output`.

Then I'm thinking probably first you name the input, and second the output, but it's the other way around what is even more confusing.

**Comment by StefMa** [comment]
It is documented.
`R` stands for `Result` while `P` stands for `Params`.
That you expect the "input" (`Params`) is the first value is just a expectation from you...

SingleUseCase
![bildschirmfoto 2018-06-11 um 14 35 21](https://user-images.githubusercontent.com/10229883/41231864-d2dd8340-6d84-11e8-938d-f4640d89be46.png)
Click on RxUseCase
![bildschirmfoto 2018-06-11 um 14 35 30](https://user-images.githubusercontent.com/10229883/41231866-d323ce54-6d84-11e8-984b-687417c17d3f.png)
Click on UseCase
![bildschirmfoto 2018-06-11 um 14 35 40](https://user-images.githubusercontent.com/10229883/41231867-d33f0822-6d84-11e8-8fb1-75ed5126de6e.png)

Do you think that isn't enough? 🤔

**Comment by Syex** [comment]
Problem is that I wouldn't check the documentation of `UseCase`. It's two classes deeper, would you?

Either copy the doc for `P` and `R` to every specific subinterface or rename them as suggested, it would be obvious to me.
